export const weatherCodeDescriptions: string[] = [];
weatherCodeDescriptions[0] = "Clear sky";
weatherCodeDescriptions[1] = "Mainly clear";
weatherCodeDescriptions[2] = "Partly cloudy";
weatherCodeDescriptions[3] = "Overcast";
weatherCodeDescriptions[45] = "Fog";
weatherCodeDescriptions[48] = "Depositing rime fog";
weatherCodeDescriptions[51] = "Light drizzle";
weatherCodeDescriptions[53] = "Moderate drizzle";
weatherCodeDescriptions[55] = "Dense drizzle";
weatherCodeDescriptions[61] = "Slight rain";
weatherCodeDescriptions[63] = "Moderate rain";
weatherCodeDescriptions[65] = "Heavy rain";
weatherCodeDescriptions[71] = "Slight snow fall";
weatherCodeDescriptions[73] = "Moderate snow fall";
weatherCodeDescriptions[75] = "Heavy snow fall";
weatherCodeDescriptions[80] = "Rain showers";
weatherCodeDescriptions[81] = "Heavy rain showers";
weatherCodeDescriptions[82] = "Violent rain showers";
weatherCodeDescriptions[95] = "Thunderstorm";
weatherCodeDescriptions[96] = "Thunderstorm with slight hail";
weatherCodeDescriptions[99] = "Thunderstorm with heavy hail";

export const getEmoji = (description: string): string => {
  if (description === "Clear sky") return "☀️";
  if (description === "Mainly clear") return "🌤️";
  if (description === "Partly cloudy") return "⛅";
  if (description === "Overcast") return "☁️";
  if (description === "Fog") return "🌫️";
  if (description === "Depositing rime fog") return "🌫️";
  if (description === "Light drizzle") return "🌦️";
  if (description === "Moderate drizzle") return "🌦️";
  if (description === "Dense drizzle") return "🌧️";
  if (description === "Slight rain") return "🌧️";
  if (description === "Moderate rain") return "🌧️";
  if (description === "Heavy rain") return "🌧️";
  if (description === "Slight snow fall") return "🌨️";
  if (description === "Moderate snow fall") return "🌨️";
  if (description === "Heavy snow fall") return "❄️";
  if (description === "Rain showers") return "🌦️";
  if (description === "Heavy rain showers") return "🌧️";
  if (description === "Violent rain showers") return "🌧️";
  if (description === "Thunderstorm") return "⛈️";
  if (description === "Thunderstorm with slight hail") return "⛈️";
  if (description === "Thunderstorm with heavy hail") return "⛈️";

  return "";
};
